from tkinter import *
from db import Db

db = Db()
db.connect()
window = Tk("My Window")
window.geometry("500x500")

title_text = StringVar()
author_text = StringVar()
year_text = StringVar()
isbn_text = StringVar()
lb_text = StringVar()
"""
title_label = Label(window, text="Title")
title_entry = Entry(window, textvariable=title_text)
author_label = Label(window, text="Author")
author_entry = Entry(window, textvariable=author_text)
year_label = Label(window, text="Year")
year_entry = Entry(window, textvariable=year_text)
isbn_label = Label(window, text="ISBN")
isbn_entry = Entry(window, textvariable=isbn_text)
listBox = Listbox(window, height=6, width=35)
sb = Scrollbar(window)
viewBtn = Button(window, text="View All", width=12)
searchBtn = Button(window, text="Search", width=12)
addBtn = Button(window, text="Add", width=12)
updateBtn = Button(window, text="Update", width=12)
deleteBtn = Button(window, text="Delete", width=12)
closeBtn = Button(window, text="Close", width=12)
title_label.grid(row=0, column=0)
title_entry.grid(row=0, column=1)
author_label.grid(row=0, column=2)
author_entry.grid(row=0, column=3)
year_label.grid(row=1, column=0)
year_entry.grid(row=1, column=1)
isbn_label.grid(row=1, column=2)
isbn_entry.grid(row=1, column=3)
listBox.grid(row=2, column=0, rowspan=6, columnspan=2)
sb.grid(row=2, column=2, rowspan=6)
listBox.configure(yscrollcommand=sb.set)
sb.configure(command=listBox.yview)
viewBtn.grid(row=2, column=3)
searchBtn.grid(row=3, column=3)
addBtn.grid(row=4, column=3)
updateBtn.grid(row=5, column=3)
deleteBtn.grid(row=6, column=3)
closeBtn.grid(row=7, column=3)


window.mainloop()
"""
print(db.get_books())
